#!/usr/bin/env python

# WS server example
import asyncio
import websockets
import base64
async def main():
    uri = "ws://localhost:5612"
    
   
    async with websockets.connect(uri) as websocket:
        
        message='CgAqACEAyztXZWxjb21lIHRvIElvVCBVRFAgU2VydmVy'
        await websocket.send(message)
        print(f"> {message }")
      
        time = await websocket.recv()
        print(time)
       

    
     
asyncio.run(main())
